# -*- coding: utf-8 -*-
"""IS211assignment2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cY-yj4frKn_A0CrTvkHn51yJcUQ3k4XM
"""

import argparse
import urllib.request
import logging
import datetime

def downloadData(url):
  with urllib.request.urlopen(url) as response:
    data = response.read().decode('utf-8')
    return data 

    pass

def processData(file):
     person_data = dict()

     for i, line in enumerate(file.split("\n")):
        if i == 0:   
            continue
        if len(line) == 0: 
            continue

        elements = line.split(",")
        id = int(elements[0])
        name = elements[1]
        try:
            birthday = datetime.datetime.strptime(elements[2], "%d/%m/%Y")
        except ValueError:
            logging.error(f"Error processing line #{i} for ID #{id}")

        person_data[id] = (name, birthday)

     return person_data
     pass

def displayPerson(id, personData):
    try:
        name, birthday = personData[id]
        print(f"Person #{id} is {name} with a birthday of {birthday:%Y-%m-%d}")
    except KeyError:
        print(f"user not found with that id# {id}")
    pass

def main(url):
    print(f"Running main with URL = {url}...")
    data  = downloadData(url)
    personData = processData(data)
    while True:
        id = int(input("Enter an ID:"))
        if id < 0:
            break
        displayPerson(id, personData)

    #parser = argparse.ArgumentParser()
   # parser.add_argument("--url", help="URL to the datafile", type=str, required=True)
   # args = parser.parse_args()

    #if __name__ == "__main__":
    #main(args.url)
main("https://s3.amazonaws.com/cuny-is211-spring2015/birthdays100.csv")